# YBDB 
# Use local_configurations.php for configurations

version: '2.1'

services:

  ybdb:
    build: .
    image: bikebike/ybdb
    container_name: ybdb
    network_mode: "bridge"
    restart: always
    ports:
      - "88:80"
    logging:
      driver: "json-file"  
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - environment
    volumes:
      - mysql:/var/lib/mysql
      - config:/var/www/html/Connections

volumes:
  mysql:
  config:
